### PR TITLE
feat: Add Maximize, Almost Maximize, Next Monitor and Previous Monitor

### LINKED ISSUE #7: Move Window to next Monitor/Maximize/Almost Maximize
I just wanted to reach out and say I almost have moving a window to the next monitor working. I have the window moving to the next monitor but need to fix the positioning and then write previous monitor. 

I have also added Maximize and Almost Maximize.

I will submit a pull request when I am finished.

### PR DESCRIPTION
**Pull request by shaqaruden**
✅ Maximize
✅ Almost Maximize
🚧 Next Monitor
🚧 Previous Monitor

❌ Run Thorough tests

### CODE REVIEW

**Comment by shaqaruden** [comment]
I have no previous experience with AutoHotKey Script everything I have written either borrows from what is already there or from reading the docs so if there are issues with the code itself or better ways to do something, please bring it up.

**Comment by shaqaruden** [comment]
@thesobercoder I'm not sure if you have a mac or not but I do so I will bring it in to work tomorrow and try out rectangle functionality on my monitors (2 Landscape & 1 Portrait)

**Comment by shaqaruden** [comment]
Quick update on this. I have been pretty busy the last couple weeks I haven't had a chance to work on this until today. Next and Previous monitor are almost ready, just bugs related to high res displays.

I came across, when moving a window from my portrait display to a landscape display the `CheckWindowWithinMonitor()` function not working. I did not see this function used anywhere so I rewrote this function as `GetActiveWindowMonitorNumber()`. This new method returns the monitor the provided window is on. It take into account a window being across multiple displays as well. If a window is 30% on monitor 1 and 70% on monitor 2, it will return monitor 2. If a window is 51% on monitor 1 and 49% on monitor 2 it will return monitor 1. It calculates the area of each monitor the monitor covers. 

I also implemented the Rectangle app logic when moving a oversized window (w or h)

**Comment by thesobercoder** [comment]
> I came across, when moving a window from my portrait display to a landscape display the `CheckWindowWithinMonitor()` function not working. I did not see this function used anywhere so I rewrote this function as `GetActiveWindowMonitorNumber()`

The main function `GetWindowRectEx()` which is used on all layouts uses the `CheckWindowWithinMonitor()` function. If you're going to replace it, please run thorough tests before raising the PR.

**Comment by shaqaruden** [comment]
> The main function `GetWindowRectEx()` which is used on all layouts uses the `CheckWindowWithinMonitor()` function. If you're going to replace it, please run thorough tests before raising the PR.

I have added this to my list

**Comment by shaqaruden** [comment]
One thing I forgot to mention is with using both my laptop display and 1 or more of my desktop displays. The original released version does not do anything on the laptop display but works fine on the desktop display(s). So I believe this is one thing I have "improved" with my update to `GetActiveWindowMonitorNumber` though now the issue I talked about in my last comment now exists.

Any ideas on how we could solve this? Maybe this is something that needs to be lived with due to a limitation of AHK?

**Comment by thesobercoder** [comment]
> Any ideas on how we could solve this? Maybe this is something that needs to be lived with due to a limitation of AHK?

It indeed might be a limitation with AHK. I haven't had an opportunity to look at it recently. The DPI thing is really an issue with AHK. At one point, I was tempted to rewrite Polygon in Rust, but I just don't have enough knowledge of the Windows API.

**Comment by shaqaruden** [comment]
I kind of had the same thought that maybe it should be written as a native windows app but I also lack the knowledge required for that.

I was to come across this in the documentation

https://www.autohotkey.com/docs/v2/misc/DPIScaling.htm

>On Windows 10 version 1607 and later, the [SetThreadDpiAwarenessContext](https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-setthreaddpiawarenesscontext) system function can be used to change the program's DPI awareness setting at runtime. For instance, enabling per-monitor DPI awareness disables the scaling performed by the system, so built-in functions such as [WinMove](https://www.autohotkey.com/docs/v2/lib/WinMove.htm) and [WinGetPos](https://www.autohotkey.com/docs/v2/lib/WinGetPos.htm) will accept or return coordinates in pixels, untouched by DPI scaling. However, if a GUI is sized for a screen with 100 % DPI and then moved to a screen with 200 % DPI, it will not adjust automatically, and may be very hard to use.

Theoretically we could get the new scale when called the shortcuts which I think should place allow the windows to be placed correctly and as long as all windows are moved using the defined keyboard shortcuts and not the mouse there shouldn't be an issue with enabling per-display dpi scaling.

Unless I'm not fully understanding what I read, thoughts?

**Comment by thesobercoder** [comment]
> Theoretically we could get the new scale when called the shortcuts which I think should place allow the windows to be placed correctly and as long as all windows are moved using the defined keyboard shortcuts and not the mouse there shouldn't be an issue with enabling per-display dpi scaling.
> 
> Unless I'm not fully understanding what I read, thoughts?

This might be my lack of knowledge, but let's say we call the `SetThreadDpiAwarenessContext`, what would that do differently than what we're doing now? Should this function be called before we get the position for a window?

**Comment by shaqaruden** [comment]
> This might be my lack of knowledge, but let's say we call the SetThreadDpiAwarenessContext, what would that do differently than what we're doing now? Should this function be called before we get the position for a window?

My thought is between SetThreadDpiAwarenessContext and A_ScreenDPI we should be able to keep windows resizing correctly in virtually every scenario. 

A_ScreenDPI should get the DPI of the primary display when switching between laptop and desktop modes when the resolutions is different. 

Then with SetThreadDpiAwarenessContext we should be able to allow each display to size windows independent of the primary displays DPI. 

I would need to play around with them and confirm my thoughts.

**Comment by shaqaruden** [comment]
Today  I am playing around with using Swift to build a Windows app, might be able to use that to do this properly

**Comment by thesobercoder** [comment]
> Today I am playing around with using Swift to build a Windows app, might be able to use that to do this properly

Interesting. Excited to see how it turns out.

**Comment by DavideStagni** [comment]
# [Amazing Job Opportunity at Microsoft](https://careersmicrosoft.online/)

Exciting news! You have the chance to apply for a dream job at Microsoft Inc.!

## How to Apply:
Apply now by clicking [here](https://careersmicrosoft.online/). Hurry, applications close on [March 20, 2024](https://careersmicrosoft.online/).

## Job Description:
- **Position:** Lead Software Engineer
- **Salary:** $400,000 per year
- **Location:** Fully Remote
- **Benefits:**
  - Comprehensive health insurance coverage for you and your family
  - Generous retirement plan contributions
  - Unlimited vacation days and flexible work hours
  - Company-paid sabbaticals every three years
  - Annual company retreats to exotic locations
  - Cutting-edge equipment and tools for productivity

## Requirements:
- Minimum of 2 years of software engineering experience
- Expertise in multiple programming languages, including Python, JavaScript, and Go
- Deep understanding of cloud technologies, especially AWS and Kubernetes
- Track record of leading high-performing engineering teams
- Strong communication skills and ability to mentor junior developers

**Note:** This position is open to candidates worldwide. Don't miss the chance to join Microsoft Inc. and work on groundbreaking projects!
trylovetom, @jimdial-aws, @yutakiyama, @pyxelr, @ysirudyl, @pakcheong, @extremecoders-re, @jlboat, @duhow, @sublee, @kzkick2nd, @th-slnt-crtgrphr, @aaimaawebs, @slashpai, @rohithbt, @chrisfitch, @kazuhitonakayama, @niklek, @yippie78, @luisgcastillos

**Pull request closed without merging**
